config/routes.rb
ShigoTrees::Application.routes.draw do
  get "pages/order_info"
  get "pages/alex"
  get "pages/home"
  get "pages/about"
  get "pages/contact"
  get "pages/scholarships"
  resources :books

   root 'pages#home'

  

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/books.rb
class Books < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
	end

	def show
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def order_info
  	@title = "Order Info"
  end

  def about
  	@title = "About Us"
  end

  def alex
  	@title = "Alex Shigo"
  end

  def contact
    @title = "Contact"
  end

  def scholarships
    @title = "Scholarships"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/books/index.html.erb
<ul class="book-list">
	<% @books.each do |book| %>
	<li class="<%= cycle('book-right', 'book-left') %>">
		<h4><%= book.long_title %></h4>
		<%= image_tag(book.image_url) %>
		<p class="desc"><%= book.description %></p>
		<span class="info"><%= link_to 'More info', book %></span>
		<span class="price">$<%= sprintf("%05.2f", book.price) %></span>
		<button class="add_to_cart" action="#">Add To Cart</button>
	</li>
	<% end %>
</ul>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %> - Shigo and Trees</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<header>
			<p id="login">Welcome [<%= link_to "Login", "#" %> | <%= link_to "Register", "#" %>] </p>
			<div class="logo"><%= image_tag "HeaderLogo.jpg", alt: "Shigo logo" %></div>
			<nav>
				<ul>
					<li class="gold"><%= link_to "Home", pages_home_path %></li>
					<li class="red"><%= link_to "Alex Shigo", pages_alex_path %></li>
					<li class="purple"><a href="#"><%= link_to "Books", books_path %></a></li>
					<li class="blue"><a href="#">CD's/DVD's</a></li>
					<li class="brown"><a href="#">Pamphlets</a></li>
					<li class="teal"><a href="#">Offshoots</a></li>
					<li class="green"><a href="#">Your Cart</a></li>
				</ul>
			</nav>
			<%= image_tag "HeaderImages.jpg", alt: "Tree images", id: "TreeImages" %>
		</header>
		<div class="info">
			<%= link_to "About Us", pages_about_path %> |
			<%= link_to "How To Place an Order", pages_order_info_path %> |
			<%= link_to "Scholarships", pages_scholarships_path %> |
			<%= link_to "Contact Us", pages_contact_path %>
		</div>
	<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="column-container">
	<h3 class="subtitle">ABOUT US</h3>
	<%= image_tag "shigofamily2.gif", alt:"Shigo family", class:"centered" %>

	<h3 class="centered">Welcome to the official website for Shigo and Trees, Associates LLC</h3>	

	<p class="about">
		Shigo and Trees, Associates was begun in 1985 by Alex and Marilyn Shigo at their home in New Hampshire. Alex had retired after more than 25 years as Chief Scientist in the US Forest Service, and had many ideas about trees and their care to share. His first book was <%= link_to "A New Tree Biology", '#' %>, a totally new vision of trees and their physiology based on his many years of tree dissections, published in 1986. For twenty years of “retirement” he traveled throughout the USA and the world giving demonstrations, making presentations, organizing workshops and educational seminars, talking with individuals, and sharing his passion about trees. In all of his encounters he encouraged people to “Touch Trees TM,” to learn about and understand trees for themselves from the inside and outside, and through the microscope. He loved trees, he loved the people who worked with trees, and strived endlessly to improve the lives of trees through his writing, his presentations, and his work with people.
	</p>

	<p class="about">
		In October 2005 Alex and Marilyn transferred Shigo and Trees, Associates to their only daughter, Judy Shigo Smith. In the transfer, the business moved across the country to the Pacific Northwest. Judy has grown up absorbing a love of forests, trees and wood. She typed her father's first book, <%= link_to "A New Tree Biology", '#'%>, as well as portions of <%= link_to "Modern Arboriculture", '#'%>. Judy now distributes the many books authored and photographed by her Dad and operates other aspects of the business from Washington. It remains, however, in a family where the science of trees is as important as the family tree: Judy's husband is Dr. Desmond Smith, known as Dr. Chips in the field of wood processing.
	</p>

	<p class="about">
		Alex's impact has been tremendous, and his philosophy has been like a breath of fresh air. His legacy is available in the volumes available on this website. Those Shigovians among us know the profound impact his teachings are having in the tree care industry, and want to share that vision of tree health and care with the broader world. Help yourself to the wealth of information available. Drink deeply from the well. Alex gave of himself to the greatest extent possible, and his gift is here for all of us to enjoy.
	</p>

	<hr>

	<p class="about subtext">"Al, Who taught me to look closely & assume nothing."</p>
	<p class="about subtext">~R. Yaple</p>
</div>

app/views/pages/alex.html.erb
<div class="column-container">
	<h3 class="subtitle">ALEX SHIGO</h3>

	<div class="col-1-3">
		<h4 class="title">Obituary</h4>
		<p>You may read the obituary for Alex Shigo and view a guest book of submitted comments at <%= link_to "Legacy", 'http://www.legacy.com' %></p>
		<hr>
		
		<h4 class="title">Publications List</h4>
		<p>This <%= link_to "FIX ME!!!!!!!", '#' %> is a comprehensive list of the books, articles, technical works and publications of Dr. Shigo.</p>
		<hr>
		
		<h4 class="title">Tribute to Dr. Shigo</h4>
		<p>"Tree Care Industry Magazine" printed a <%= link_to "Tribute to the Legendary Dr. Alex Shigo", 'http://tcia.org/PDFs/TCI_Mag_Nov_06.pdf' %> in their November 2006 issue.  Read about his <em>Undaunted Enthusiasm</em>, as well as his <em>Connections... With Trees and People.</em></p>
		<hr>

		<h4 class="title">National Arts Club</h4>
		<p>If you are in New York, please visit the <%= link_to "National Arts Club", 'http://www.nationalartsclub.org/' %> at 15 Gramercy Park South in Manhattan.  There, hanging in the Gregg Gallery and in adjacent hallways, are a series of quotations by Alex Shigo on tree care and philosophy.  This display was created in support of Arbor Day and has become a permanent exhibit.</p>
	</div>
	
	<div class="col-2-3">
		<%= image_tag 'dralexshigo2.gif', alt: 'Alex Shigo', class: 'shigo-right' %>
		<p class="date">May 8, 1930 - October 6, 2006</p>
		<p>
			DUBBED THE "FATHER OF MODERN ARBORICULTURE", Dr. Alex Shigo has spent most of his adult life studying, lecturing, dissecting and writing about trees. "A tree is much more than a chunk of dead wood," exclaims Shigo. "Trees are alive; they live all year 'round, not just for a short time in the summer." They work during the winter, too. Many people spend time on what goes wrong with a tree; I wanted to study what goes right."
		</p>
		<p>
			Shigo was born at the height of the depression in 1930, in Duquesne, Pennsylvania. Attending Waynesburg College in Southwestern Pennsylvania, he received his Bachelor of Science degree in biology. Music was also a part of Shigo's life; he plays a mean clarinet. But his future plans were interrupted by the Korean War; he served in the Air Force and was in the official Air Force Band. After the war, Shigo continued his study of botany, biology and genetics, working as a lab assistant for Dr. Charles Bryner, his biology teacher at Waynesburg College.  Bryner expected quite a bit from Shigo, admonishing him whenever he missed a question, Shigo recalls. "It helped me become more disciplined," he quips.
		</p>	
		<p>
			 Shigo furthered his education at the University of West Virginia, receiving a master's degree in biology in 1958, and a Ph.D. in pathology in 1960. He completed the doctorate so quickly because he started working on his Ph.D research at the same time he was working on his master's - "a loop- hole the university quickly closed," recalls Shigo.
		</p>
		<p>
			His career as a pathologist began with the U.S. Forest Service later that year. "I was a creature of opportunities," Shigo notes. "Until the 1950s there were only big two-man chain saws; then a manageable, one-man chain saw was developed. One of my assignments for the U.S. Forest Service was to learn more about tree decay. So I went out and started to dissect trees."
		</p>
		<p>
			Shigo had never handled a chain saw before. Even so, he wasn't satisfied with the cross-cut or transverse type of dissection that other pathologists favored. "Such dissection provides only a part of a tree's story," remarks Shigo.
		</p>
		<p>
			His idea was to dissect trees longitudinally as well. As a result, he learned that many commonly-held concepts about heart rot and decomposition and other theories were wrong. "I could either go with the book (theories) or go with what I saw in the tree. Either the books were wrong or the trees were wrong. I chose to go with the trees," Shigo says.
		</p>
		<%= image_tag "shigo-historical.jpg", alt:"Shigo in woods", class: "shigo-left" %>
		<p>
			"I started to see trees in a different way because a tree is a living thing," Shigo explains. "When you hit a living thing, it reacts. When YOU hit a tree, it does something. When a tree is threatened, it doesn't just stand there. It establishes boundaries."
		</p>
		<p>
			With these and other theories that go against conventions, Shigo admits he has his detractors, but he also has his admirers. Denne Goldstein, publisher of this magazine [Irrigation & Green Industry], was the founder of Arbor Age magazine. He developed a relationship with Dr. Shigo in the late 1970s. "Alex is one of the most knowledgeable people about trees; he is an exciting lecturer. His enthusiasm is contagious."
		</p>
		<p>
			Not one to mince words, Shigo has earned the respect of the foresters andarborists around the world. "Too many people are working in the fieldwithout an understanding of trees and grass," he observed.
		</p>
		<p>
			 "People should know that trees are generating organisms, instead of re-generating organisms like human beings," Shigo explains. "Trees generate their own food from carbon dioxide, sunlight and water, while human beings must intake food from elsewhere. Therefore, tree food is a misnomer. While such supplements, like fertilizer, provide important elements, they do not provide an energy source," he says.
		</p>
		<p>
			Another example: While humans put new cells in old places countless times during a lifetime, trees continue to put new cells in new places, Shigo explains. Similarly, a tree doesn't heal, because it doesn't replace injured cells with new ones.
		</p>
		<p>
			 In his books and lectures, Dr. Shigo disagrees with other popular theories about trees. Among those theories that Shigo disputes is the idea that trees are mostly dead wood.
		</p>
		<p>
			 Shigo's understanding of trees comes from his years in the U.S. Forest Service. He eventually became chief scientist for the Forest Service and was in demand as a speaker at many conferences, both in the United States as well as around the world, until he retired in 1985.
		</p>
		<p>
			 Not one to sit back and do nothing, he began to write and continued to play music. It wasn't long before calls began coming in from around the world, requesting him to lecture and teach. Shigo began a second career as a lecturer and author, which continues until this day.
		</p>
		<p>
			 "The name Alex Shigo has a become a legend. When he walks into a room, he is the focal point. He has aura that commands respect," commented Goldstein.
		</p>
		<p>
			"Dr. Shigo is one of the warmest people I've met, with a sincere desire to teach what he has learned about trees. 'You have to touch a tree and feel it,' is one of my favorite Shigoisms."
		</p>
		<p>
			Since his retirement, he's written and published many papers, journals, and books, published as Shigo and Trees, Associates. He’s also assembled 5,000 slides from his work during the last 40-plus years onto a CD, “Trees, Associates and Shigo.” Included on the disk are thousands of images of the insides of trees, some so close up that one can see dust mites on an insect.While he's reluctant to discuss exact figures, Shigo said he's sold more than 70 tons of books, enough to cover the driveway of his home several times over. 
		</p>
		<p>
			Shigo and his wife, Marilyn, live in Durham, New Hampshire. They have a son, a daughter, five grandchildren and one great-grandson. 
		</p>
		<hr>
		<p>
			<em>On October 6, 2006 Alex died at home in Barrington. A memorial service was held at The Sugar Shack, site of his local educational workshops, and attended by many who have learned from, worked with, and admired him from around the country and around the world.</em>
		</p>
		<hr>
		<p>
			"There is now an Al Shigo shaped hole in the Universe."
   ~ T. Meekins
		</p>
	</div>
</div>

app/views/pages/contact.html.erb
<h3 class="subtitle">Contact Us</h3>
<p class="contact">Shigo and Trees, Associates LLC</p>
<p class="contact">PO Box 2466</p>
<p class="contact">Snohomish, WA 98291-2466 USA</p>
<p class="contact">Phone: 1 360-862-1869</p>
<p class="contact">Fax: 1 360-862-8490</p>
<p class="contact">Email: judy@shigoandtrees.com</p>
<p class="contact"><%= link_to "Shigo and Trees", root_path %></p>

app/views/pages/home.html.erb
<%= image_tag "touchtrees.gif", alt:"Touch Trees", class:'touchtrees' %>

<div class="announcement">
	<p>A NEW Publication from Shigo and Trees, Associates:</p>
	<p>Soul of a Tree: Conversations with Alex Shigo on the Nature of Tree Care</p>
	<p>By Jack Philips</p>
	<p>See "How to Place an Order" above if you have any questions or concerns about shipping rates or delivery times.</p>
</div>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/pages/order_info.html.erb
 <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>

  <div id="tabs">
  <ul>
    <li><a href="#tabs-1">Ways To Order</a></li>
    <li><a href="#tabs-2">Order Form</a></li>
    <li><a href="#tabs-3">Payment</a></li>
    <li><a href="#tabs-4">Bulk/Discounts</a></li>
    <li><a href="#tabs-5">Shipping</a></li>
    <li><a href="#tabs-6">Return Policy</a></li>
  </ul>
  <div id="tabs-1">
    <p>An order may be placed in one of several ways, whichever is most convenient for you. See Payment information.</p>
    
		<ol>
			<li>Directly from this website, click on any of the categories above and select items for purchase. Submit your request and Visa or MasterCard payment details.</li>
			<li>Send an e-mail with your request, shipping information and credit card payment details. You may split your credit card information across two or more successive messages.</li>
			<li>Phone the number below and leave pertinent information, including a return phone number in case there are any questions. Please speak clearly.</li>
			<li>Fax your request with contact and shipping information and credit card payment details.</li>
			<li>Purchase Order from a company or business sent either as a fax, e-mail attachment or through the mail.</li>
			<li>Order Form sent as a fax, e-mail attachment or through the mail.</li>
		</ol>
  </div>
  <div id="tabs-2">
    <p> 
    	To order books, pamphlets and CD's/DVD's, click to view and/or print the <%= link_to "order form", "/images/web_order_form_list_Jan_13.jpg", target: :blank %>. To order t-shirts and bumper stickers click to view and/or print the <%= link_to "t-shirts and bumper stickers order form", "/images/t-shirts_bmprstkrs_order_form_Jan_13.jpg", target: :blank %>. The forms may also be completed and returned via e-mail attachment or fax.
    </p>
  </div>
  <div id="tabs-3">
		
		<ul>
				<li> Payment must be in US dollars.</li>
				<li> 
					Wire transfers or checks must be <u>received</u> for the full amount of the purchase; any bank fees or transfer expenses are the responsibility of the buyer. 
				</li>
		
			<li>	
				Credit Card Processing - Be sure that the billing address matches the credit card in use.  The most cost-effective shipping rate (see Shipping information) will be used and will be reflected on your credit card receipt. An e-mailed credit card receipt will be generated on acceptance of the payment. A hard copy receipt will be included with the shipment, along with a full receipt of the complete order.
			</li>
		</ul>
  </div>
  <div id="tabs-4">
  	<p>
  		Some items are priced by quantity or grouping.  Please be sure to check for your best rate.  If you are a book store, reseller, educational institution, or other group that will order frequently or in quantities, please <%= link_to "contact", pages_contact_path %> Shigo and Trees for possible discounts.
  	</p>
  	<p>
  		Please be sure to note the quantity pricing on pamphlets when completing your order.  These rates are:
  	</p>
  	<table>
  		<tr>
  			<td><u>Copies</u></td>
  			<td><u>Price</u></td>
  		</tr>
  		<tr>
  			<td>1-9</td>
  			<td>$3.00 ea</td>
  		</tr>
  		<tr>
  			<td>10-99</td>
  			<td>$2.00 ea</td>
  		</tr>
  		<tr>
  			<td>100-999</td>
  			<td>$1.50 ea</td>
  		</tr>
  		<tr>
  			<td>1000+</td>
  			<td>$1.00 ea</td>
  		</tr>
  	</table>
  	<p>
  		See the <%= link_to "order form", "/images/web_order_form_list_Jan_13.jpg", target: :blank %> for other price groups.
  	</p>
  	
  	<ul>
  		<li>
  	  		<%= link_to "Dr. Shigo's Tree Series FIX", "#" %> is sold as a single item and is comprised of one copy each of the nine hard and soft covered books: <%= link_to "100 Tree Myths FIX", "#" %>, <%= link_to "Modern Arboriculture FIX", "#" %>, <%= link_to "New Tree Biology and Dictionary set FIX", "#" %>, <%= link_to "The Nature of Tree Care: Conversations with Alex Shigo FIX", "#" %>, <%= link_to "Tree Anatomy FIX", "#" %>, <%= link_to "Tree Basics FIX", "#" %>, <%= link_to "Tree Pithy Points FIX", "#" %>, <%= link_to "Tree Pruning FIX", "#" %>, <%= link_to "Tree Pruning Basics FIX", "#" %>.  The series is $278 and represents a 20% discount from the individually priced items.
  	  	</li>
  	  	
  	  	
  	  	<li>
  	  		The <%= link_to "Complete Library FIX", "#" %> of Shigo and Trees, Associates includes one copy each of the nine books, as well as one each of the four pamphlets, plus one each of the <%= link_to "Backyard Pathology DVD FIX", "#" %>, <%= link_to "Trees, Associates and Shigo CD of 5,000 photos FIX", "#" %>, and <%= link_to "The Alex L. Shigo Story DVD FIX", "#" %> at $428, representing a 20% discount from the individually priced items.
  	  	</li>
  	  </ul>
  	
  </div>
  <div id="tabs-5">
  	<ul>
  		<li>Shipping options are UPS or US Postal Service</li> 
  		<li>
  			Most items will ship via US Postal Service "flat rate" packaging where appropriate, as this service is usually the most cost-effective and quickest.
  		</li> 
  		<li>
  			Large overseas shipments may be shipped via a freight carrier. If you have a preference for how you would like your order shipped, please so note when placing your order, otherwise the most cost-effective method will be used. Pricing is dependent on the size and weight of the order.
  		</li> 
  		<li>
  			In some cases, a better rate may be available and your payment will reflect a reduced charge (see some pricing examples below).
  		</li> 
  		<li>
  			Shipping reflects current postal service and other rates only. Shipping costs DO NOT include any brokerage, customs or other fees that may be assessed by the delivery company or the country's postal service. If delivery requires the payment of any additional fees, these fees are the responsibility of the buyer.
  		</li> 
  		<li>
  			Shipment is typically within the week of order placement, excluding weekends and holidays. Your order will not ship: 
  			<ol>
  				<li>if there are difficulties processing your credit card</li> 
  				<li>if you do not include any shipping costs</li> 
  				<li>if you do not provide sufficient address information</li>
  				<li>if you request verification of shipping costs to your credit card before order processing</li>
  				<li>during weekends or holidays</li>
  			</ol>
  		</li>
  	</ul>

		<p>Sample Shipping Rates for items OUTSIDE the USA (actual rates may vary depending on quantity of items ordered):</p>		
		<ul>
			<li>
				1 copy <%= link_to "Modern Arboriculture FIX LINK", "#" %> or 1 copy <%= link_to "A New Tree Biology and Dictionary FIX LINK","#" %> - $22 to Canada, $26 to all other countries
			</li>
			<li>1 set <%= link_to "Complete Library FIX LINK", "#" %> - $43 to Canada, $62 to all other countries</li>
		</ul>
  </div>
  <div id="tabs-6">
  	<ul>
  		<li>Returns may be made only after <%= link_to "contacting", pages_contact_path %> Shigo and Trees, Associates LLC prior to item return.</li>
  		<li>All return items must be shipped at sender’s expense.</li> 
  		<li>All return items must be received in like new condition without marks, stickers or tags, or damage of any kind.</li> 
  		<li>Items that are sold as a set or grouping must be returned in total.</li> 
  		<li>A 15% restocking fee will be deducted from the refund due.</li><li>Return requests must be made within 30 days of order receipt.</li>
  		<li>All items are copyrighted material and may not be copied in any way.</li> 
  		<li>Refunds will be made by check unless originally paid by credit card, in which case you must state that a credit card refund is preferred.</li>
  	</ul>
  </div>
</div>

app/views/pages/scholarships.html.erb
<h3 class="subtitle">Scholarships</h3>

<div class="column-container"><p class="about">There are many who would like to support and continue the research and education efforts of Alex Shigo.  Dr. Shigo believed in learning about trees from the inside and outside with consideration and appreciationof how they live, grow and use energy, their environment, and proper care.  To further the education of students of all ages and stages, the following scholarships are being established.  Please contact these organizations if you would like to make a contribution or application.</p>

<br>
<h3 class="centered">Paul Smith's College - Paul Smiths, NY</h3>
<p class="about">Contact: Hillarie Logan-Dechene, Vice President for Institutional Advancement</p>
<p class="about">PO Box 265</p>
<p class="about">Paul Smiths, NY 12970</p>
<p class="about">800-421-2605</p>
<p class="about">dechenh@paulsmiths.edu</p>
<p class="about">For memorial contributions or scholarship applications, please contact the Forestry Department</p>
<br>

<h3 class="centered">Waynesburg College - Waynesburg, PA</h3>
<p class="about">Contact: Karen Elliott Galentine, Director of Development Waynesburg College</p>
<p class="about">51 West College Street</p>
<p class="about">Waynesburg, PA 15370</p>
<p class="about">724-852-3369</p>
<p class="about">www.waynesburg.edu</p>
<p class="about">For scholarship applications, contact the Biology Department directly.</p></div>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>